### ISSUE TITLE
Examples of tablePattern

### ISSUE THREAD

**Issue by DivekJohns** [redwert/pg-dump-restore#1]
Hi, I am trying to use `tablePattern` option

Example table names I'm trying to match` [ UserManagementSystem, UserLoginSystem, UserSessionSystem ]`

what I have tried is `tablePattern="User*"` but no match is found

`pg_dump: error: no matching tables were found`

**or** 

how to achieve something like `pg_dump myDatabase -t table1 -t table2 > backup.sql;`

Any help appreciated

**Comment by redwert** [comment]
Hi, actually try to achieve this using postrgess cli. The module is only a wrapper and it passes the arguments to cli. I included all possible options and that's it. There is no any extra logic aly passing arguments to cli

**Comment by atlanteh** [comment]
@redwert some arguments should be converted to arrays as they can occur multiple times in the cli (like excludeTablePattern)

**Comment by redwert** [comment]
@atlanteh welcome to make a pull request with changes

**Comment by redwert** [comment]
Will update version with this changes tomorrow

**Comment by redwert** [comment]
done

**Comment by atlanteh** [comment]
Thanks @redwert
By the way, if you want to be thorough and you have time, there are a couple more options that can be used more than once..
Just look for the term "more than once" in the [pg-dump](https://www.postgresql.org/docs/current/app-pgdump.html) and [pg-restore](https://www.postgresql.org/docs/current/app-pgrestore.html) docs
Again, thanks!

**Comment by redwert** [comment]
@atlanteh, thanks will take a look
