### ISSUE TITLE
availability of a new version

### ISSUE THREAD

**Issue by jasv18** [redwert/pg-dump-restore#10]
Hi, I hope you have a nice day. I have made a pull request that extends the ability to exlude table data patters[https://github.com/redwert/pg-dump-restore/pull/9](url), so since it was approved, i was wondering if these changes were released, because I made a npm of this package and it doesn't have them. Thank you for any help you can offer me.

**Comment by redwert** [comment]
Hm, strange. I will check tomorrow. I thought that new changes is in new version.

**Comment by jasv18** [comment]
ok thanks for your time and patience

**Comment by redwert** [comment]
Published the new version 1.0.11

**Comment by jasv18** [comment]
I already reviewed it, thanks for your time
