### ISSUE TITLE
how to use it with knex?

### ISSUE THREAD

**Issue by edgardoll4** [redwert/pg-dump-restore#11]
First of all, thank you for your contribution.

I am using strapi, which from what I have seen uses knex as orm, I would like to know how I can use it with knex instead of sequelize.

**Comment by redwert** [comment]
sequelize is in dev-dependencies only to run tests. The module functionality itself doesn't use it at all. So use npm install --omit=dev

**Comment by redwert** [comment]
sequelize is in dev-dependencies only to run tests. The module functionality itself doesn't use it at all. So use npm install --omit=dev

**Comment by edgardoll4** [comment]
I have a suggestion to put in the code so that the backup can be created with INSERT instead of COPY, since with COPY it gave me an error when backing up and I created the backup with the extension .slq.

add it to the package index on line 32 >>> args.push("--column-inserts");

![image](https://github.com/redwert/pg-dump-restore/assets/32710186/c73bbc53-9a94-4b00-b6ae-eb7f961adf96)

**Comment by edgardoll4** [comment]
![image](https://github.com/redwert/pg-dump-restore/assets/32710186/07311d91-d61d-4226-8841-bc8744baf4dc)
 
I added another parameter in the index, it is to see if that feature can be added in the next version.

**Comment by redwert** [comment]
Welcome to create pull request with needed changes
